name: Development

on: [ push, pull_request ]

jobs:
  install_shop:
    strategy:
      matrix:
        edition: [ 'CE', 'EE' ]
        php: [ '7.4', '8.0' ]
        mysql: [ '5.7' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Clone testing environment master
        run: git clone --depth 1 https://github.com/OXID-eSales/docker-eshop-sdk.git --branch master --single-branch .

      - name: Clone the shop (${{ github.ref_name }})
        if: github.event_name == 'push'
        run: git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch ${{ github.ref_name }} --single-branch source

      - name: Clone the shop (PR ${{ github.event.number }})
        if: github.event_name == 'pull_request'
        run: |
          git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch ${{ github.base_ref }} --single-branch source
          git -C source fetch origin refs/pull/${{ github.event.number }}/head:pr_${{ github.event.number }}
          git -C source checkout pr_${{ github.event.number }}

      - name: Cache current installation
        uses: actions/cache@v2
        with:
          path: |
            ./*
          key: shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}

      - name: Prepare container configuration
        run: |
          make setup
          make addbasicservices
          make file=services/selenium-firefox.yml addservice
          perl -pi\
              -e "s#PHP_VERSION=.*#PHP_VERSION='${{ matrix.php }}'#g;"\
              -e "s#MYSQL_VERSION=.*#MYSQL_VERSION='${{ matrix.mysql }}'#g;"\
              .env
          perl -pi\
              -e 's#display_errors =.*#display_errors = false#g;'\
              -e 'print "xdebug.max_nesting_level=1000\nxdebug.mode=coverage\n\n";'\
              -e 'print "error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING\n"'\
              containers/php/custom.ini
          perl -pi\
              -e 's#/var/www/#/var/www/source/#g;'\
              containers/httpd/project.conf

      - name: Prepare shop configuration
        run: |
          cp source/source/config.inc.php.dist source/source/config.inc.php
          perl -pi\
            -e 'print "SetEnvIf Authorization \"(.*)\" HTTP_AUTHORIZATION=\$1\n\n" if $. == 1'\
            source/source/.htaccess
          perl -pi\
            -e 's#<dbHost>#mysql#g;'\
            -e 's#<dbUser>#root#g;'\
            -e 's#<dbName>#example#g;'\
            -e 's#<dbPwd>#root#g;'\
            -e 's#<dbPort>#3306#g;'\
            -e 's#<sShopURL>#http://localhost.local/#g;'\
            -e 's#<sShopDir>#/var/www/source/#g;'\
            -e 's#<sCompileDir>#/var/www/source/tmp/#g;'\
            source/source/config.inc.php

      - name: Create logs directory
        run: mkdir -p logs

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Define PE & EE versions
        if: matrix.edition == 'EE'
        run: |
          if [[ "${{ github.ref_name }}" == *"master"* || "${{ github.base_ref }}" == *"master"* ]]; then PE_VERSION=dev-master && EE_VERSION=dev-master; fi
          if [[ "${{ github.ref_name }}" == *"b-7.0.x"* || "${{ github.base_ref }}" == *"b-7.0.x"* ]]; then PE_VERSION=dev-b-7.0.x && EE_VERSION=dev-b-7.0.x; fi
          if [[ "${{ github.ref_name }}" == *"b-6.5.x"* || "${{ github.base_ref }}" == *"b-6.5.x"* ]]; then PE_VERSION=dev-b-6.5.x && EE_VERSION=dev-b-6.5.x; fi
          if [[ "${{ github.ref_name }}" == *"b-6.4.x"* || "${{ github.base_ref }}" == *"b-6.4.x"* ]]; then PE_VERSION=dev-b-6.4.x && EE_VERSION=dev-b-6.4.x; fi
          echo "PE_VERSION=$PE_VERSION" >> $GITHUB_ENV
          echo "EE_VERSION=$EE_VERSION" >> $GITHUB_ENV

      - name: Require PE (${{ env.PE_VERSION }}) & EE (${{ env.EE_VERSION }})
        if: matrix.edition == 'EE'
        run: |
          docker-compose run -T --rm php composer config github-protocols https
          docker-compose run -T --rm php composer config -g github-oauth.github.com ${{ secrets.GH_CI_JENKINS_TOKEN }}
          docker-compose run -T --rm php composer config repositories.oxid-esales/oxideshop-ee git https://github.com/OXID-eSales/oxideshop_ee.git
          docker-compose run -T --rm php composer config repositories.oxid-esales/oxideshop-pe git https://github.com/OXID-eSales/oxideshop_pe.git
          docker-compose run -T --rm php composer require oxid-esales/oxideshop-pe:${{ env.PE_VERSION }} --no-update
          docker-compose run -T --rm php composer require oxid-esales/oxideshop-ee:${{ env.EE_VERSION }} --no-update --no-plugins --no-scripts

      - name: Install dependencies
        run: docker-compose exec -T php composer update --no-interaction

      - name: Reset shop
        run: docker-compose exec -T php php vendor/bin/reset-shop

      - name: Stop containers
        run: |
          docker-compose down
          sleep 2

  unit_tests:
    strategy:
      matrix:
        edition: [ 'CE', 'EE' ]
        php: [ '7.4', '8.0' ]
        mysql: [ '5.7' ]
      fail-fast: false
    needs: [ install_shop ]
    runs-on: ubuntu-latest
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
          key: shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}
          restore-keys: |
            shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Run tests (CE)
        if: matrix.edition == 'CE'
        run: |
          docker-compose run -T --rm \
            -e XDEBUG_MODE=coverage \
            -e TEST_DIRS=unit,Unit \
            php php vendor/bin/runtests | tee unit_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' unit_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Run tests (EE)
        if: matrix.edition == 'EE'
        run: |
          docker-compose run -T --rm \
            -e XDEBUG_MODE=coverage \
            -e TEST_DIRS=unit,Unit \
            -e ADDITIONAL_TEST_PATHS=vendor/oxid-esales/oxideshop-ee/Tests,vendor/oxid-esales/oxideshop-pe/Tests \
            php php vendor/bin/runtests | tee unit_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' unit_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Upload PHPUnit Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-logs
          path: unit_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt
          if-no-files-found: error
          retention-days: 7

  integration_tests:
    strategy:
      matrix:
        edition: [ 'CE', 'EE' ]
        php: [ '7.4', '8.0' ]
        mysql: [ '5.7' ]
      fail-fast: false
    needs: [ install_shop ]
    runs-on: ubuntu-latest
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
          key: shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}
          restore-keys: |
            shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Run tests (CE)
        if: matrix.edition == 'CE'
        run: |
          docker-compose run -T --rm \
            -e XDEBUG_MODE=coverage \
            -e TEST_DIRS=integration,Integration \
            php php vendor/bin/runtests | tee integration_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Run tests (EE)
        if: matrix.edition == 'EE'
        run: |
          docker-compose run -T --rm \
            -e XDEBUG_MODE=coverage \
            -e TEST_DIRS=integration,Integration \
            -e ADDITIONAL_TEST_PATHS=vendor/oxid-esales/oxideshop-ee/Tests,vendor/oxid-esales/oxideshop-pe/Tests \
            php php vendor/bin/runtests | tee integration_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error' integration_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Upload PHPUnit Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-logs
          path: integration_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt
          if-no-files-found: error
          retention-days: 7

  codeception_tests:
    strategy:
      matrix:
        edition: [ 'CE', 'EE' ]
        php: [ '7.4', '8.0' ]
        mysql: [ '5.7' ]
      fail-fast: false
    needs: [ install_shop ]
    runs-on: ubuntu-latest
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
          key: shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}
          restore-keys: |
            shopInstallation-${{ matrix.edition }}-${{ matrix.php }}-${{ matrix.mysql }}-${{ github.sha }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Run tests (CE)
        if: matrix.edition == 'CE'
        run: |
          docker-compose exec -T \
            -e SELENIUM_SERVER_HOST=seleniumfirefox \
            -e BROWSER_NAME=firefox \
            php php vendor/bin/runtests-codeception --ext DotReporter | tee codeception_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' codeception_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Run tests (EE)
        if: matrix.edition == 'EE'
        run: |
          docker-compose exec -T \
            -e SELENIUM_SERVER_HOST=seleniumfirefox \
            -e BROWSER_NAME=firefox \
            -e ADDITIONAL_TEST_PATHS=vendor/oxid-esales/oxideshop-ee/Tests,vendor/oxid-esales/oxideshop-pe/Tests \
            php php vendor/bin/runtests-codeception --ext DotReporter | tee codeception_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt 2>&1 || true
          if grep -q -Ei 'fail|\\.\\=\\=|Warning|Notice|Deprecated|Fatal|Error|DID NOT FINISH' codeception_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt; then exit 1; fi

      - name: Upload PHPUnit Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-logs
          path: codeception_${{ matrix.edition }}_PHP${{ matrix.php }}_MYSQL${{ matrix.mysql }}_phpunit_log.txt
          if-no-files-found: error
          retention-days: 7

      - name: Upload Codeception Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: codeception-artifacts-${{ matrix.edition }}-PHP${{ matrix.php }}-MYSQL${{ matrix.mysql }}
          path: source/tests/Codeception/_output/*
          if-no-files-found: ignore
          retention-days: 7